export { default as Actor } from './Actors/Actors'
export { default as Profile } from './Profile/Profile'
export { default as MovieInformation } from './MovieInformation/MovieInformation'
export { default as Movies } from './Movies/Movies'
export { default as Navbar } from './Navbar/Navbar'
